# PiShutdown project Makefile
# Author: Krzysztof Dziuba krzysztof (at) meeqo.net
# License: LGPL-3.0

SKELETON_BASE = ../../cortex-skeleton
DEVICE_MODEL = STM32F030F4
PROJECT = test

CSRC += config.c sysevent.c led.c serial.c eventqueue.c main.c



include $(SKELETON_BASE)/cortex-skeleton.mk